### ISSUE TITLE
Add .Net

### ISSUE THREAD

**Issue by Gorniv** [DenisIzmaylov/awesome-telegram-bots#6]
Library
[MrRoundRobin-bot](https://github.com/MrRoundRobin/telegram.bot) -C# library to talk to Telegrams Bot API
[TLSharp](https://github.com/sochix/TLSharp) -Telegram (http://telegram.org) client library implemented in C#. Only basic functionality is currently implemented.
Example
[MrRoundRobin-example](https://github.com/MrRoundRobin/telegram.bot.examples) - example MrRoundRobin-bot

**Comment by DenisIzmaylov** [comment]
Thank you
